source "https://rubygems.org"

ruby "3.2.3"
gem "rails", "~> 7.1.3", ">= 7.1.3.4"
gem "sqlite3", "~> 1.4"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false
gem "rack-cors"
gem "rest-client"
gem "bcrypt"
gem 'dotenv-rails', groups: [:development, :test]
gem "pry-rails"
gem "pry"
gem "firebase"
gem 'mysql2', '>= 0.5.3', '< 0.6.0'

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
end

group :development do

end

